# Generated by Django 3.1.7 on 2021-05-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210509_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
