# Generated by Django 3.1.7 on 2021-05-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210510_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('img_abs_path', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subsciption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fst_name', models.CharField(max_length=256)),
                ('snd_name', models.CharField(max_length=256)),
                ('mail', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=32)),
                ('promo', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='color',
        ),
        migrations.RemoveField(
            model_name='events',
            name='desc',
        ),
    ]
