version: "3.9"

services:
    django:
        build: .
        env_file: .env
        ports:
            - 8000:8000/tcp
        volumes:
            - type: volume
              source: data
              target: /var/data
              volume:
                  nocopy: true
            - type: bind
              source: .
              target: /usr/src/app

volumes:
    data:
