name: frontend

on:
  push:
    branches:
      - 'frontend'

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start DockerFile
      run: docker build -t frontend frontend/

    - name: Start Docker-compose
      run: docker-compose up -d --build

    - name: Stop docker
      run: docker-compose down