name: Backend

on:
  push:
    branches:
      - 'backend'

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start DockerFile
      run: docker build -t frontend .

    - name: Start Docker-compose
      run: docker-compose up

    - name: Stop docker
      run: docker-compose down